### ISSUE TITLE
Item description not showing after adding new expense item

### ISSUE THREAD

**Issue by nadin3amanda** [nadin3amanda/new-project#3]
Item description not showing after adding new expense item

![image](https://user-images.githubusercontent.com/85320612/138654665-57b50899-40e9-4a1b-86a3-07d4e92d32cd.png)

**Comment by dacster13** [comment]
The issue is due to line 12 of ExpenseForm.js

`setEnteredTitle(event.target.values);`

should instead be

`setEnteredTitle(event.target.value);`

**Comment by nadin3amanda** [comment]
Merged and working. Thank you
![image](https://user-images.githubusercontent.com/85320612/139180664-0f354bed-724f-4089-b7f4-d5fad40cfad5.png)
